version: '3.8'

services:
  app:
    build: .
    container_name: shahwatweb

    labels:
      - traefik.enable=true
      - traefik.http.routers.shahwat.rule=Host(`sh.dpinfoserver.co.in`)
      - traefik.http.routers.shahwat.entrypoints=websecure
      - traefik.http.routers.shahwat.tls=true
      - traefik.http.services.shahwat.loadbalancer.server.port=3002